pyproject.toml, scripts/lint.sh, tests/assets/multi_func.py, tests/test_completion_run.py, tests/test_multi_func.py, tests/test_sub_completion.py, typer_cli/main.py
=> Upgrade Typer

README.md, pyproject.toml
:memo: Sync `README.md` with Typer.
=> Sync README.md with Typer

README.md, pyproject.toml
:arrow_up: Upgrade Typer to 0.1.0
=> Upgrade Typer to 0.1.0

pyproject.toml
:arrow_up: Upgrade Typer version
=> Upgrade Typer version

.github/dependabot.yml, .github/workflows/issue-manager.yml
🔧 Update GitHub actions and add Dependabot
=> 🔧 Update GitHub actions

tests/assets/multi_app.py, tests/assets/multiapp-docs.md, tests/test_doc.py, typer_cli/main.py
=> Arguments Section in Automatic Docs for CLI Arguments

tests/assets/multi_app.py, tests/assets/multiapp-docs.md, typer_cli/main.py
✅ Update docs tests to include other defaults
=> ✅ Update docs tests to include other defaults

.github/workflows/latest-changes.yml, release-notes.md
👷 Add Latest Changes GitHub Action
=> 👷 Add Latest Changes GitHub Action

release-notes.md
=> 🔊 Debug latest changes action

release-notes.md
🐛 Fix latest changes GitHub Action
=> 🐛 Fix latest changes GitHub Action

pyproject.toml, release-notes.md
=> 🔖 Release version 0.0.11

.github/dependabot.yml
👷 Upgrade Dependabot, include GitHub Actions
=> 👷 Upgrade Dependabot, include GitHub Actions

.github/FUNDING.yml, .github/workflows/issue-manager.yml, .github/workflows/latest-changes.yml
👷 Upgrade GitHub Actions, add funding config
=> 👷 Upgrade GitHub Actions, add funding config

.coveragerc, .github/workflows/smokeshow.yml, .github/workflows/test.yml, scripts/test.sh
👷 Migrate CI coverage to Smokeshow and include alls-green
=> 👷 Migrate CI coverage to Smokeshow and include alls-green

README.md
=> 📝 Update badges on README

.github/workflows/test.yml, pyproject.toml
⬆️ Enable tests and classifiers for Python 3.11
=> ⬆️ Enable tests and classifiers for Python 3.11

.github/workflows/latest-changes.yml
💚 Fix latest-changes release notes GitHub Action
=> 💚 Fix latest-changes release notes GitHub Action

.github/workflows/latest-changes.yml
💚 Fix latest-changes GitHub Action, strike two ⚾
=> 💚 Fix latest-changes GitHub Action, strike two ⚾

.github/workflows/latest-changes.yml
👷 Tweak latest-changes GitHub Action when running as a workflow dispatch
=> 👷 Tweak latest-changes GitHub Action when running as a workflow dispatch

.github/workflows/latest-changes.yml
👷 Update tokens for tmate and latest changes
=> 👷 Update tokens for tmate and latest changes
